title = Dragon Ball: Infinite Legacy
description = RPG cooperativo de mundo aberto no universo de Dragon Ball. Crie seu guerreiro, domine o Ki, voe, lute e evolua.
author = dbil
default_mapgen = v7
disallowed_mapgens = v6
